### ISSUE TITLE
下载完成没有调起安装 android9.0

### ISSUE THREAD

**Issue by 382202771** [itlwy/AppSmartUpdate#1]
你好，下载完成后没有调起安装程序界面 是哪里需要修改么？没有报错也。

**Comment by itlwy** [comment]
应该是9.0 申请权限问题

**Comment by 382202771** [comment]
这个库还会一直更新适配么，现在适配到多少了，多谢了！很好用，我看我能不能改了了

**Comment by 382202771** [comment]
加了个权限就好了  多谢！<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>

**Comment by 382202771** [comment]
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>

**Comment by 382202771** [comment]
android:name="android.permission.REQUEST_INSTALL_PACKAGES"
