### ISSUE TITLE
新合成的包MD5跟新包的MD5 不匹配

### ISSUE THREAD

**Issue by 739923259** [itlwy/AppSmartUpdate#3]
使用后台服务生成的patch包跟更新文件，代码跑完之后一直提示新合成的包MD5跟新包的MD5 不匹配
 更新开始
11-13 13:32:33.883 3420-3727/? I/ApkPatchLibrary: old = /data/app/com.lwy.appsmartupdate-1/base.apk 
11-13 13:32:33.883 3420-3727/? I/ApkPatchLibrary: new = /storage/emulated/0/Android/data/com.lwy.appsmartupdate/files/update/102.apk 
11-13 13:32:33.883 3420-3727/? I/ApkPatchLibrary: patch = /storage/emulated/0/Android/data/com.lwy.appsmartupdate/files/update/101to102.patch 
11-13 13:32:33.883 3420-3727/? I/ApkPatchLibrary: -------test /storage/emulated/0/Android/data/com.lwy.appsmartupdate/files/update/101to102.patch 
11-13 13:32:33.884 3420-3727/? I/ApkPatchLibrary: <<<<<<<<<< 
11-13 13:32:33.884 3420-3727/? I/ApkPatchLibrary: ++++++++test /storage/emulated/0/Android/data/com.lwy.appsmartupdate/files/update/101to102.patch 
11-13 13:32:33.922 3420-3727/? I/ApkPatchLibrary: applypatch result = 0 
11-13 13:32:33.936 3420-3727/? D/SignUtils: file's md5=dbb4075b49de796e243ff8a08dddf749, real md5=b54d746906fac35903d0700eba622595
11-13 13:32:33.936 3420-3727/? D/com.lwy.smartupdate: onError: 合成完毕，但是合成得到的apk MD5不对！

**Comment by itlwy** [comment]
1.用github的服务端生成的还是你自己生成的?
2.用来生成差分包的旧apk确保是手机上安装的那个
3.如果是自己生成的差分包，请注意清单文件上的新apk的md5值是不是正确填写

**Comment by 739923259** [comment]
用github 服务端生成的，那些东西都没错我可以确定。配置好几次了。哥能不能加下QQ 739923259 我把具体的给你看

**Comment by 739923259** [comment]
> 1.用github的服务端生成的还是你自己生成的?
> 2.用来生成差分包的旧apk确保是手机上安装的那个
> 3.如果是自己生成的差分包，请注意清单文件上的新apk的md5值是不是正确填写



> 1.用github的服务端生成的还是你自己生成的?
> 2.用来生成差分包的旧apk确保是手机上安装的那个
> 3.如果是自己生成的差分包，请注意清单文件上的新apk的md5值是不是正确填写

用github 服务端生成的，那些东西都没错我可以确定。配置好几次了。哥能不能加下QQ 739923259 我把具体的给你看

**Comment by 739923259** [comment]
差分包是用github上的服务端生成的，配置什么都是根据服务端生成的，但是就是提示MD5不匹配，哥能加下QQ? 739923259我的具体的文件给你看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"itlwy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 上午10:02
收件人:&nbsp;"itlwy/AppSmartUpdate"<AppSmartUpdate@noreply.github.com&gt;;
抄送:&nbsp;"waiting"<739923259@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [itlwy/AppSmartUpdate] 新合成的包MD5跟新包的MD5 不匹配 (#3)




1.用github的服务端生成的还是你自己生成的?
 2.用来生成差分包的旧apk确保是手机上安装的那个
 3.如果是自己生成的差分包，请注意清单文件上的新apk的md5值是不是正确填写

**Comment by 739923259** [comment]
我用github服务端生成的差分包有问题，我自己下载了一个生成差分包的工具生成的差分包可以用，但是我自己生成的差分包我只改了一行代码，差分包有1M多，github服务端代码生成差分包只有145字节。求解答，希望大佬能加我QQ，一起探讨下

**Comment by itlwy** [comment]
你把新、旧apk，用提供的服务端程序生成的patch文件，安装旧的apk，试下自动更新，如果还是提示md5不对的问题，就在pc端用bsdiff(可以找个库，或者把源码编译一下运行)把旧的apk和patch文件合成新的apk，再看下合成的md5和原来那个新apk是否一致，一致则android端的合成代码有问题，不一致则可能是服务端生成patch有问题

**Comment by 739923259** [comment]
我自己下的disff库生成的patch文件可以。服务端代码生成的patch不可以。但是我自己下载的disff库生成的patch文件比较大，其实我都没改代码，只是改了下版本号，生成的patch文件有1M多。哥要不要试下你传的代码？我的安卓端，跟服务器是直接拿你的gitbhub项目跑的------------------ 原始邮件 ------------------
发件人: "itlwy"<notifications@github.com>
发送时间: 2019年11月16日(星期六) 下午5:13
收件人: "itlwy/AppSmartUpdate"<AppSmartUpdate@noreply.github.com>;
抄送: "739923259"<739923259@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [itlwy/AppSmartUpdate] 新合成的包MD5跟新包的MD5 不匹配 (#3)



你把新、旧apk，用提供的&#x670D;务端程序生成的patch文&#x4EF6;，安装旧的apk，试下自动更新，如果还是提示md5不对的问题，就在pc端用bsdiff(可以找个库，或者把源码编译一下运行)把旧的apk和patch文&#x4EF6;合成新的apk，再看下合成的md5和原来那个新apk是否一致，一致则android端的合成代码有问题，不一致则可能是&#x670D;务端生成patch有问题
 
&mdash;

**Comment by itlwy** [comment]
服务端的代码的bsdiff用的是三方的库，我这边试是可以的，也可能是作者后面有更新,你install下来的库是新的版本，可以确认下版本号，你或者写个步骤或小视频发到qq邮箱: 9011532@qq.com上帮你看下

**Comment by 739923259** [comment]
我是这样生成增量文件的，默认的配置文件如下
{
&nbsp; &nbsp; "minVersion": 0,
&nbsp; &nbsp; "minAllowPatchVersion": 0,
&nbsp; &nbsp; "newVersion": 0,
&nbsp; &nbsp; "tip": "",
&nbsp; &nbsp; "apkURL": "",
&nbsp; &nbsp; "hash": "",
&nbsp; &nbsp; "patchInfo": {
&nbsp; &nbsp; },
&nbsp; &nbsp; "size": 0
}

1、我运行项目，选择版本apk文件100app-release ，发布版本号填写100
如下图



项目的配置文件变成如下
{
    "minVersion": 100,
    "minAllowPatchVersion": 100,
    "newVersion": 100,
    "tip": "100apk",
    "apkURL": "100app-release.apk",
    "hash": "806be63881befc0ce9d784945833432c",
    "patchInfo": {}
}
接下来我先去把101app-release的apk拷贝到服务端的app目录下，然后再从文件夹选择101app-release，发布版本号填写101（如果我直接选择服务端下的101app-release会报apk不存在）如下图





然后服务端的清单文件就会生成如下图



我把增量文件部署到七牛的服务器上，模拟器上安装旧的100app-release.apk，合成后提示MD5不正确。
我把服务器生成的增量文件，与旧的100app-release.apk&nbsp;用自己下载的bsdiff库合成，发现新合成的apkMD5跟 101app-release不一样。
如果我把100app-release.apk 与 101app-release.apk用我自己下载的库生成增量文件，合成之后apk就可以正常使用。


上面三个附件一个是服务端代码，一个是我自己下的bsdiff ，一个是android端的代码。谢谢哥帮我看下哪里错误


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"itlwy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月16日(星期六) 晚上9:49
收件人:&nbsp;"itlwy/AppSmartUpdate"<AppSmartUpdate@noreply.github.com&gt;;
抄送:&nbsp;"waiting"<739923259@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [itlwy/AppSmartUpdate] 新合成的包MD5跟新包的MD5 不匹配 (#3)




服务端的代码的bsdiff用的是三方的库，我这边试是可以的，也可能是作者后面有更新,你install下来的库是新的版本，可以确认下版本号，你或者写个步骤或小视频发到qq邮箱: 9011532@qq.com上帮你看下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

App-Update-Server-master.zip (12.66M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=323962316f5f0ccd586c781d12360b1d00095000030009044e0b0357511b0d505b0a4f0852035b1f53095453560f5854525f5306342a397313494f64445258460614315446405c404e54034240534b1c1950123109&t=exs_ftn_download&code=c9b14692




bsdiff.zip (73.1K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0e6538370dbfcccb0a30221b4264001b07015a52545354521c510f535449060c095515565652571906565c52535d060006070802646e325642015151024a485d416505&t=exs_ftn_download&code=1e87dd24




AppSmartUpdate-master.zip (34.01M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2a62646340d4e8cd5f377e4f4532051f0254555b055302024951015b521f0305535a49015004531d525a5752070b560501515d51632b37711412370e0240436514060517061f5a51171601114d485e40645f&t=exs_ftn_download&code=dbdcc270

**Comment by 739923259** [comment]
上次的文件名称必须一样。就不会出现MD5不一致的问题
